-- ####################################################
-- SCRIPT 0: RESETAR TUDO (LIMPAR E RECOMEÇAR)
-- Execute este script quando tiver erro ORA-00001
-- ####################################################

PROMPT ============================================
PROMPT    RESETANDO BANCO DE DADOS
PROMPT ============================================

-- Passo 1: DELETAR TODOS OS DADOS (ordem correta por causa das FKs)
PROMPT Deletando dados das tabelas...

DELETE FROM T_EASEHC_ORIENTACAO;
DELETE FROM T_EASEHC_HISTORICO;
DELETE FROM T_EASEHC_CANREM;
DELETE FROM T_EASEHC_CONSULTA;
DELETE FROM T_EASEHC_MED_ESP;
DELETE FROM T_EASEHC_LOCALIZACAO;
DELETE FROM T_EASEHC_ESPECIALIDADE;
DELETE FROM T_EASEHC_MEDICO;
DELETE FROM T_EASEHC_PACIENTE;

COMMIT;
PROMPT Dados deletados com sucesso!

-- Passo 2: DROPAR AS SEQUENCES (se existirem)
PROMPT Deletando sequences antigas...

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_PACIENTE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_MEDICO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_ESPECIALIDADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_LOCALIZACAO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_CONSULTA';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_CANREM';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_HISTORICO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_ORIENTACAO';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

COMMIT;
PROMPT Sequences deletadas com sucesso!

-- Passo 3: VERIFICAR SE ESTÁ LIMPO
PROMPT 
PROMPT Verificando se está tudo limpo...
PROMPT 

SELECT 'PACIENTES' AS TABELA, COUNT(*) AS QTD FROM T_EASEHC_PACIENTE
UNION ALL
SELECT 'MEDICOS', COUNT(*) FROM T_EASEHC_MEDICO
UNION ALL
SELECT 'ESPECIALIDADES', COUNT(*) FROM T_EASEHC_ESPECIALIDADE
UNION ALL
SELECT 'LOCALIZACOES', COUNT(*) FROM T_EASEHC_LOCALIZACAO
UNION ALL
SELECT 'CONSULTAS', COUNT(*) FROM T_EASEHC_CONSULTA;

PROMPT 
PROMPT ============================================
PROMPT    RESET COMPLETO!
PROMPT    Agora execute:
PROMPT    1) @1_CRIAR_SEQUENCES.sql
PROMPT    2) @2_INSERIR_DADOS_TESTE.sql
PROMPT ============================================

-- ####################################################
-- FIM DO SCRIPT
-- ####################################################

