-- ####################################################
-- SCRIPT 2: INSERIR DADOS DE TESTE
-- Execute DEPOIS de criar as sequences (script 1)
-- ####################################################

-- ==================== PACIENTES ====================
INSERT INTO T_EASEHC_PACIENTE (ID_PACIENTE, NM_COMPLETO, DT_NASC, GENERO, TELEFONE, TP_SANGUINEO, ALERGIAS)
VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Ana Silva', TO_DATE('1985-03-12','YYYY-MM-DD'), 'F', '11988880001', 'O+', 'Nenhuma');

INSERT INTO T_EASEHC_PACIENTE (ID_PACIENTE, NM_COMPLETO, DT_NASC, GENERO, TELEFONE, TP_SANGUINEO, ALERGIAS)
VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Bruno Santos', TO_DATE('1990-07-01','YYYY-MM-DD'), 'M', '11977770002', 'A+', 'Asma');

INSERT INTO T_EASEHC_PACIENTE (ID_PACIENTE, NM_COMPLETO, DT_NASC, GENERO, TELEFONE, TP_SANGUINEO, ALERGIAS)
VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Carla Mendes', TO_DATE('1978-11-30','YYYY-MM-DD'), 'F', '11333330003', 'B-', 'Penicilina');

INSERT INTO T_EASEHC_PACIENTE (ID_PACIENTE, NM_COMPLETO, DT_NASC, GENERO, TELEFONE, TP_SANGUINEO, ALERGIAS)
VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Daniel Oliveira', TO_DATE('1982-05-20','YYYY-MM-DD'), 'M', '11222220004', 'AB+', 'Nenhuma');

INSERT INTO T_EASEHC_PACIENTE (ID_PACIENTE, NM_COMPLETO, DT_NASC, GENERO, TELEFONE, TP_SANGUINEO, ALERGIAS)
VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Eduarda Ramos', TO_DATE('1995-09-09','YYYY-MM-DD'), 'F', '11444440005', 'O-', 'Frutos do mar');

-- ==================== MÉDICOS ====================
INSERT INTO T_EASEHC_MEDICO (ID_MEDICO, NM_COMPLETO, CRM, TELEFONE, EMAIL)
VALUES (SEQ_EASEHC_MEDICO.NEXTVAL, 'Dr. Marcos Lima', 'CRM12345', '1123456789', 'marcos.lima@easehc.com');

INSERT INTO T_EASEHC_MEDICO (ID_MEDICO, NM_COMPLETO, CRM, TELEFONE, EMAIL)
VALUES (SEQ_EASEHC_MEDICO.NEXTVAL, 'Dra. Paula Rocha', 'CRM23456', '1123456790', 'paula.rocha@easehc.com');

INSERT INTO T_EASEHC_MEDICO (ID_MEDICO, NM_COMPLETO, CRM, TELEFONE, EMAIL)
VALUES (SEQ_EASEHC_MEDICO.NEXTVAL, 'Dr. Rafael Nunes', 'CRM34567', '1123456791', 'rafael.nunes@easehc.com');

-- ==================== ESPECIALIDADES ====================
INSERT INTO T_EASEHC_ESPECIALIDADE (ID_ESP, NM_ESP, AREA_MED, TP_MED_CONS)
VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Cardiologia', 'Cardio', 30);

INSERT INTO T_EASEHC_ESPECIALIDADE (ID_ESP, NM_ESP, AREA_MED, TP_MED_CONS)
VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Pediatria', 'Infantil', 20);

INSERT INTO T_EASEHC_ESPECIALIDADE (ID_ESP, NM_ESP, AREA_MED, TP_MED_CONS)
VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Clínica Médica', 'Geral', 20);

INSERT INTO T_EASEHC_ESPECIALIDADE (ID_ESP, NM_ESP, AREA_MED, TP_MED_CONS)
VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Dermatologia', 'Pele', 25);

INSERT INTO T_EASEHC_ESPECIALIDADE (ID_ESP, NM_ESP, AREA_MED, TP_MED_CONS)
VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Ortopedia', 'Ossos', 40);

-- ==================== LOCALIZAÇÕES ====================
INSERT INTO T_EASEHC_LOCALIZACAO (ID_LOCAL, NM_UNIDADE, ENDERECO, ESTADO, CIDADE, PAIS, HR_FUNC, TELEFONE)
VALUES (SEQ_EASEHC_LOCALIZACAO.NEXTVAL, 'Unidade Centro', 'Rua A, 100', 'SP', 'São Paulo', 'Brasil', 'Seg-Sex 08:00-18:00', '1133333000');

INSERT INTO T_EASEHC_LOCALIZACAO (ID_LOCAL, NM_UNIDADE, ENDERECO, ESTADO, CIDADE, PAIS, HR_FUNC, TELEFONE)
VALUES (SEQ_EASEHC_LOCALIZACAO.NEXTVAL, 'Unidade Norte', 'Av. B, 200', 'SP', 'São Paulo', 'Brasil', 'Seg-Sex 08:00-17:00', '1133333001');

INSERT INTO T_EASEHC_LOCALIZACAO (ID_LOCAL, NM_UNIDADE, ENDERECO, ESTADO, CIDADE, PAIS, HR_FUNC, TELEFONE)
VALUES (SEQ_EASEHC_LOCALIZACAO.NEXTVAL, 'Unidade Sul', 'R. C, 300', 'SP', 'São Paulo', 'Brasil', 'Seg-Sex 09:00-18:00', '1133333002');

-- ==================== CONSULTAS ====================
INSERT INTO T_EASEHC_CONSULTA (ID_CONSULTA, ID_PACIENTE, ID_MEDICO, ID_LOCAL, ID_ESP, DT_HORA, DUR_MINUTOS, STATUS, OBSERVACOES, PRIORIDADE)
VALUES (SEQ_EASEHC_CONSULTA.NEXTVAL, 1, 1, 1, 1, TO_TIMESTAMP('2025-12-01 09:00:00','YYYY-MM-DD HH24:MI:SS'), 30, 'Agendada', 'Consulta de rotina', 'Normal');

INSERT INTO T_EASEHC_CONSULTA (ID_CONSULTA, ID_PACIENTE, ID_MEDICO, ID_LOCAL, ID_ESP, DT_HORA, DUR_MINUTOS, STATUS, OBSERVACOES, PRIORIDADE)
VALUES (SEQ_EASEHC_CONSULTA.NEXTVAL, 2, 2, 2, 2, TO_TIMESTAMP('2025-12-02 10:30:00','YYYY-MM-DD HH24:MI:SS'), 45, 'Agendada', NULL, 'Alta');

INSERT INTO T_EASEHC_CONSULTA (ID_CONSULTA, ID_PACIENTE, ID_MEDICO, ID_LOCAL, ID_ESP, DT_HORA, DUR_MINUTOS, STATUS, OBSERVACOES, PRIORIDADE)
VALUES (SEQ_EASEHC_CONSULTA.NEXTVAL, 3, 3, 3, 3, TO_TIMESTAMP('2025-12-03 14:00:00','YYYY-MM-DD HH24:MI:SS'), 20, 'Agendada', 'Retorno', 'Normal');

-- ==================== TABELA ASSOCIATIVA ====================
INSERT INTO T_EASEHC_MED_ESP (ID_MEDICO, ID_ESP) VALUES (1, 1);
INSERT INTO T_EASEHC_MED_ESP (ID_MEDICO, ID_ESP) VALUES (1, 3);
INSERT INTO T_EASEHC_MED_ESP (ID_MEDICO, ID_ESP) VALUES (2, 2);
INSERT INTO T_EASEHC_MED_ESP (ID_MEDICO, ID_ESP) VALUES (3, 3);
INSERT INTO T_EASEHC_MED_ESP (ID_MEDICO, ID_ESP) VALUES (3, 1);

COMMIT;

-- Verificar dados inseridos
SELECT 'PACIENTES' AS TABELA, COUNT(*) AS QTD FROM T_EASEHC_PACIENTE
UNION ALL
SELECT 'MEDICOS', COUNT(*) FROM T_EASEHC_MEDICO
UNION ALL
SELECT 'ESPECIALIDADES', COUNT(*) FROM T_EASEHC_ESPECIALIDADE
UNION ALL
SELECT 'LOCALIZACOES', COUNT(*) FROM T_EASEHC_LOCALIZACAO
UNION ALL
SELECT 'CONSULTAS', COUNT(*) FROM T_EASEHC_CONSULTA;

-- ####################################################
-- FIM DO SCRIPT
-- ####################################################

