
-- ###################################################################
-- PROJETO EASEHC - DDL + DML + DQL (Oracle)
-- Arquivo: projeto_easehc_oracle.sql
-- ###################################################################
-- 1) CRIAÇÃO DE TABELAS (DDL)


-- TABELA PACIENTE
CREATE TABLE T_EASEHC_PACIENTE (
  ID_PACIENTE    NUMBER      NOT NULL,
  NM_COMPLETO    VARCHAR2(100),
  DT_NASC        DATE,
  GENERO         CHAR(1),
  TELEFONE       VARCHAR2(15),
  TP_SANGUINEO   VARCHAR2(3),
  ALERGIAS       VARCHAR2(255),
  CONSTRAINT PK_PACIENTE PRIMARY KEY (ID_PACIENTE),
  CONSTRAINT CK_PAC_GENERO CHECK (GENERO IN ('F','M','O')),
  CONSTRAINT CK_PAC_SANGUE CHECK (TP_SANGUINEO IN ('A+','A-','AB+','AB-','B+','B-','O+','O-')),
  CONSTRAINT UK_PAC_NOME UNIQUE (NM_COMPLETO)
);

-- TABELA MEDICO
CREATE TABLE T_EASEHC_MEDICO (
  ID_MEDICO   NUMBER      NOT NULL,
  NM_COMPLETO VARCHAR2(100),
  CRM         VARCHAR2(20),
  TELEFONE    VARCHAR2(15),
  EMAIL       VARCHAR2(100),
  CONSTRAINT PK_MEDICO PRIMARY KEY (ID_MEDICO),
  CONSTRAINT UK_MED_CRM UNIQUE (CRM),
  CONSTRAINT UK_MED_EMAIL UNIQUE (EMAIL)
);

-- TABELA ESPECIALIDADE
CREATE TABLE T_EASEHC_ESPECIALIDADE (
  ID_ESP    NUMBER      NOT NULL,
  NM_ESP    VARCHAR2(100),
  AREA_MED  VARCHAR2(100),
  TP_MED_CONS NUMBER,
  CONSTRAINT PK_ESPECIALIDADE PRIMARY KEY (ID_ESP)
);

-- TABELA ASSOCIATIVA MEDICO-ESPECIALIDADE (muitos-para-muitos)
CREATE TABLE T_EASEHC_MED_ESP (
  ID_MEDICO NUMBER NOT NULL,
  ID_ESP    NUMBER NOT NULL,
  CONSTRAINT PK_MED_ESP PRIMARY KEY (ID_MEDICO, ID_ESP)
);

-- TABELA LOCALIZACAO
CREATE TABLE T_EASEHC_LOCALIZACAO (
  ID_LOCAL   NUMBER      NOT NULL,
  NM_UNIDADE VARCHAR2(100),
  ENDERECO   VARCHAR2(200),
  ESTADO     CHAR(2),
  CIDADE     VARCHAR2(100),
  PAIS       VARCHAR2(100),
  HR_FUNC    VARCHAR2(100),
  TELEFONE   VARCHAR2(15),
  CONSTRAINT PK_LOCAL PRIMARY KEY (ID_LOCAL)
);

-- TABELA CONSULTA
CREATE TABLE T_EASEHC_CONSULTA (
  ID_CONSULTA   NUMBER      NOT NULL,
  ID_PACIENTE   NUMBER      NOT NULL,
  ID_MEDICO     NUMBER      NOT NULL,
  ID_LOCAL      NUMBER      NOT NULL,
  ID_ESP        NUMBER      NOT NULL,
  DT_HORA       TIMESTAMP,
  DUR_MINUTOS   NUMBER,
  STATUS        VARCHAR2(20),
  OBSERVACOES   VARCHAR2(255),
  PRIORIDADE    VARCHAR2(20),
  CONSTRAINT PK_CONSULTA PRIMARY KEY (ID_CONSULTA),
  CONSTRAINT CK_CONS_STATUS CHECK (STATUS IN ('Agendada','Cancelada','Realizada')),
  CONSTRAINT CK_CONS_PRIOR CHECK (PRIORIDADE IN ('Alta','Baixa','Normal'))
);

-- TABELA CANCELAMENTO / REMARCAÇÃO
CREATE TABLE T_EASEHC_CANREM (
  ID_AJUSTE     NUMBER      NOT NULL,
  ID_CONSULTA   NUMBER      NOT NULL,
  TP_AJUSTE     VARCHAR2(20),
  MOT_SOLIC     VARCHAR2(255),
  NV_DT_HORA    TIMESTAMP,
  CONSTRAINT PK_CANREM PRIMARY KEY (ID_AJUSTE),
  CONSTRAINT CK_CANREM_TP CHECK (TP_AJUSTE IN ('Cancelada','Remarcacao'))
);

-- TABELA HISTORICO MEDICO
CREATE TABLE T_EASEHC_HISTORICO (
  ID_HIST   NUMBER      NOT NULL,
  ID_PAC    NUMBER      NOT NULL,
  DIAGNOST  VARCHAR2(255),
  TRATAM    VARCHAR2(255),
  MEDICACAO VARCHAR2(255),
  OBS_HIST  VARCHAR2(255),
  DATA_ACESS DATE,
  CONSTRAINT PK_HIST PRIMARY KEY (ID_HIST)
);

-- TABELA ORIENTACAO (exames / orientações por consulta)
CREATE TABLE T_EASEHC_ORIENTACAO (
  ID_ORIENT   NUMBER      NOT NULL,
  ID_CONSULTA NUMBER      NOT NULL,
  TP_EXAME    VARCHAR2(100),
  INS_PREP    VARCHAR2(255),
  REC_POS     VARCHAR2(255),
  CONSTRAINT PK_ORIENT PRIMARY KEY (ID_ORIENT)
);
  

ALTER TABLE T_EASEHC_MED_ESP
  ADD CONSTRAINT FK_MEDESP_MED FOREIGN KEY (ID_MEDICO)
    REFERENCES T_EASEHC_MEDICO (ID_MEDICO);

ALTER TABLE T_EASEHC_MED_ESP
  ADD CONSTRAINT FK_MEDESP_ESP FOREIGN KEY (ID_ESP)
    REFERENCES T_EASEHC_ESPECIALIDADE (ID_ESP);

ALTER TABLE T_EASEHC_CONSULTA
  ADD CONSTRAINT FK_CONS_PAC FOREIGN KEY (ID_PACIENTE)
    REFERENCES T_EASEHC_PACIENTE (ID_PACIENTE);

ALTER TABLE T_EASEHC_CONSULTA
  ADD CONSTRAINT FK_CONS_MED FOREIGN KEY (ID_MEDICO)
    REFERENCES T_EASEHC_MEDICO (ID_MEDICO);

ALTER TABLE T_EASEHC_CONSULTA
  ADD CONSTRAINT FK_CONS_ESP FOREIGN KEY (ID_ESP)
    REFERENCES T_EASEHC_ESPECIALIDADE (ID_ESP);

ALTER TABLE T_EASEHC_CONSULTA
  ADD CONSTRAINT FK_CONS_LOC FOREIGN KEY (ID_LOCAL)
    REFERENCES T_EASEHC_LOCALIZACAO (ID_LOCAL);

ALTER TABLE T_EASEHC_CANREM
  ADD CONSTRAINT FK_CAN_CONS FOREIGN KEY (ID_CONSULTA)
    REFERENCES T_EASEHC_CONSULTA (ID_CONSULTA);

ALTER TABLE T_EASEHC_HISTORICO
  ADD CONSTRAINT FK_HIST_PAC FOREIGN KEY (ID_PAC)
    REFERENCES T_EASEHC_PACIENTE (ID_PACIENTE);

ALTER TABLE T_EASEHC_ORIENTACAO
  ADD CONSTRAINT FK_ORI_CONS FOREIGN KEY (ID_CONSULTA)
    REFERENCES T_EASEHC_CONSULTA (ID_CONSULTA);



