-- ####################################################
-- SOLUÇÃO DEFINITIVA: LIMPAR TUDO E COMEÇAR DO ZERO
-- Execute este script e pronto!
-- ####################################################

PROMPT ============================================
PROMPT    LIMPANDO TUDO...
PROMPT ============================================

-- PASSO 1: DELETAR TODOS OS DADOS
DELETE FROM T_EASEHC_ORIENTACAO;
DELETE FROM T_EASEHC_HISTORICO;
DELETE FROM T_EASEHC_CANREM;
DELETE FROM T_EASEHC_CONSULTA;
DELETE FROM T_EASEHC_MED_ESP;
DELETE FROM T_EASEHC_LOCALIZACAO;
DELETE FROM T_EASEHC_ESPECIALIDADE;
DELETE FROM T_EASEHC_MEDICO;
DELETE FROM T_EASEHC_PACIENTE;
COMMIT;

PROMPT ✓ Dados deletados

-- PASSO 2: DELETAR SEQUENCES
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_PACIENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_MEDICO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_ESPECIALIDADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_LOCALIZACAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_CONSULTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_CANREM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_HISTORICO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EASEHC_ORIENTACAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT ✓ Sequences deletadas

-- PASSO 3: CRIAR SEQUENCES NOVAS
CREATE SEQUENCE SEQ_EASEHC_PACIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_MEDICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_ESPECIALIDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_LOCALIZACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_CONSULTA START WITH 1001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_CANREM START WITH 5001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_HISTORICO START WITH 9001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EASEHC_ORIENTACAO START WITH 8001 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT ✓ Sequences criadas

-- PASSO 4: INSERIR DADOS DE TESTE
PROMPT Inserindo dados de teste...

-- PACIENTES
INSERT INTO T_EASEHC_PACIENTE VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Ana Silva', TO_DATE('1985-03-12','YYYY-MM-DD'), 'F', '11988880001', 'O+', 'Nenhuma');
INSERT INTO T_EASEHC_PACIENTE VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Bruno Santos', TO_DATE('1990-07-01','YYYY-MM-DD'), 'M', '11977770002', 'A+', 'Asma');
INSERT INTO T_EASEHC_PACIENTE VALUES (SEQ_EASEHC_PACIENTE.NEXTVAL, 'Carla Mendes', TO_DATE('1978-11-30','YYYY-MM-DD'), 'F', '11333330003', 'B-', 'Penicilina');

-- MÉDICOS
INSERT INTO T_EASEHC_MEDICO VALUES (SEQ_EASEHC_MEDICO.NEXTVAL, 'Dr. Marcos Lima', 'CRM12345', '1123456789', 'marcos.lima@easehc.com');
INSERT INTO T_EASEHC_MEDICO VALUES (SEQ_EASEHC_MEDICO.NEXTVAL, 'Dra. Paula Rocha', 'CRM23456', '1123456790', 'paula.rocha@easehc.com');
INSERT INTO T_EASEHC_MEDICO VALUES (SEQ_EASEHC_MEDICO.NEXTVAL, 'Dr. Rafael Nunes', 'CRM34567', '1123456791', 'rafael.nunes@easehc.com');

-- ESPECIALIDADES
INSERT INTO T_EASEHC_ESPECIALIDADE VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Cardiologia', 'Cardio', 30);
INSERT INTO T_EASEHC_ESPECIALIDADE VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Pediatria', 'Infantil', 20);
INSERT INTO T_EASEHC_ESPECIALIDADE VALUES (SEQ_EASEHC_ESPECIALIDADE.NEXTVAL, 'Clínica Médica', 'Geral', 20);

-- LOCALIZAÇÕES
INSERT INTO T_EASEHC_LOCALIZACAO VALUES (SEQ_EASEHC_LOCALIZACAO.NEXTVAL, 'Unidade Centro', 'Rua A, 100', 'SP', 'São Paulo', 'Brasil', 'Seg-Sex 08:00-18:00', '1133333000');
INSERT INTO T_EASEHC_LOCALIZACAO VALUES (SEQ_EASEHC_LOCALIZACAO.NEXTVAL, 'Unidade Norte', 'Av. B, 200', 'SP', 'São Paulo', 'Brasil', 'Seg-Sex 08:00-17:00', '1133333001');
INSERT INTO T_EASEHC_LOCALIZACAO VALUES (SEQ_EASEHC_LOCALIZACAO.NEXTVAL, 'Unidade Sul', 'R. C, 300', 'SP', 'São Paulo', 'Brasil', 'Seg-Sex 09:00-18:00', '1133333002');

-- CONSULTAS
INSERT INTO T_EASEHC_CONSULTA VALUES (SEQ_EASEHC_CONSULTA.NEXTVAL, 1, 1, 1, 1, TO_TIMESTAMP('2025-12-01 09:00:00','YYYY-MM-DD HH24:MI:SS'), 30, 'Agendada', 'Consulta de rotina', 'Normal');
INSERT INTO T_EASEHC_CONSULTA VALUES (SEQ_EASEHC_CONSULTA.NEXTVAL, 2, 2, 2, 2, TO_TIMESTAMP('2025-12-02 10:30:00','YYYY-MM-DD HH24:MI:SS'), 45, 'Agendada', NULL, 'Alta');

-- TABELA ASSOCIATIVA
INSERT INTO T_EASEHC_MED_ESP VALUES (1, 1);
INSERT INTO T_EASEHC_MED_ESP VALUES (2, 2);
INSERT INTO T_EASEHC_MED_ESP VALUES (3, 3);

COMMIT;

PROMPT ✓ Dados inseridos

-- PASSO 5: VERIFICAR
PROMPT 
PROMPT ============================================
PROMPT    RESULTADO:
PROMPT ============================================

SELECT 'PACIENTES' AS TABELA, COUNT(*) AS QTD FROM T_EASEHC_PACIENTE
UNION ALL
SELECT 'MEDICOS', COUNT(*) FROM T_EASEHC_MEDICO
UNION ALL
SELECT 'ESPECIALIDADES', COUNT(*) FROM T_EASEHC_ESPECIALIDADE
UNION ALL
SELECT 'LOCALIZACOES', COUNT(*) FROM T_EASEHC_LOCALIZACAO
UNION ALL
SELECT 'CONSULTAS', COUNT(*) FROM T_EASEHC_CONSULTA;

PROMPT 
PROMPT Pacientes cadastrados:
SELECT ID_PACIENTE, NM_COMPLETO, TELEFONE FROM T_EASEHC_PACIENTE;

PROMPT 
PROMPT Próximo ID que será usado:
SELECT SEQ_EASEHC_PACIENTE.CURRVAL AS ULTIMO_ID,
       SEQ_EASEHC_PACIENTE.NEXTVAL AS PROXIMO_ID
FROM DUAL;

-- Voltar um valor pois consumimos um NEXTVAL
ALTER SEQUENCE SEQ_EASEHC_PACIENTE INCREMENT BY -1;
SELECT SEQ_EASEHC_PACIENTE.NEXTVAL FROM DUAL;
ALTER SEQUENCE SEQ_EASEHC_PACIENTE INCREMENT BY 1;

PROMPT 
PROMPT ============================================
PROMPT    ✅ PRONTO! Agora teste o sistema Java
PROMPT ============================================

-- ####################################################
-- FIM DO SCRIPT
-- ####################################################

